import type { Metadata } from 'next'
import './globals.css'
import { AuthProvider } from '@/components/auth-provider'
import { Header } from '@/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body>
        {/* AuthProvider はセッション（ログイン状態）をコンポーネントに共有するために必要 */}
        <AuthProvider>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-grow p-4 sm:p-6 lg:p-8">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
