import type { Metadata } from 'next'
import './globals.css'
import { AuthProvider } from '@/components/auth-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body>
        {/* AuthProvider はセッション（ログイン状態）をコンポーネントに共有するために必要 */}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
